[package]
name = "einntol"
version = "0.1.0"
edition = "2024"
authors = ["liavunn <liavunn@users.noreply.github.com>"]
description = "A universal toolkit"
license = "Apache-2.0"
repository = "https://github.com/liavunn/einntol"
keywords = ["cli", "utility", "rust"]
categories = ["command-line-utilities"]

[dependencies]
miette = "7.6"
fastrand = "2"
thiserror = "2.0"
wyhash = "0.6"
sysinfo = "0.38"
ignore = "0.4"
bitflags = "2"
serde = { version = "1.0", features = ["derive"] }
iced = "0.14"
tokio = { version = "1.52", features = ["full"]}

[features]


[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = "z"
